# Generated by Django 4.2.6 on 2023-10-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
