# Generated by Django 4.2.6 on 2023-10-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_point_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
