# Generated by Django 4.2.6 on 2023-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_point_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
